// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttxswlubudlsigtemlah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0eHN3bHVidWRsc2lndGVtbGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTc2MzAsImV4cCI6MjA2ODk5MzYzMH0.T2o1TVlXRdqg8bpZJA0QhwfXzweU7dkDL-H40EX_bXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});